apps_path: /apps
primary_domain: kiria-f.ru
shadow_domain: allrensys.com
gh_secrets: "{{ gh_secrets_json | from_json }}"

deployment:
  allrensys:
    - fornex
  bashrc:
    - fornex
  bio:
    - fornex
  couchdb:
    - fornex
  grafana:
    - fornex
  node_exporter:
    - fornex
  prometheus:
    - fornex
  traefik:
    - fornex
