apps_path: /apps
primary_domain: telepovs.com
shadow_domain: telepovs.com
gh_secrets: "{{ gh_secrets_json_base64 | b64decode | from_json }}"
gh_vars: "{{ gh_vars_json_base64 | b64decode | from_json }}"

deployment:
  allrensys:
    - fornex
  bashrc:
    - fornex
  bio:
    - aws
  couchdb:
    - fornex
  grafana:
    - fornex
  node_exporter:
    - fornex
  prometheus:
    - fornex
  traefik:
    - aws

acceess:
  kiria-f:
    - fornex
    - aws
  kiria-f-alt:
    - aws