services:
  telepovs:
    image: ghcr.io/kiria-f-alt/html-service-plug:latest
    container_name: telepovs
    restart: 'unless-stopped'
    networks:
      - proxy
    labels:
      traefik.enable: 'true'
      traefik.http.routers.telepovs.rule: 'Host(`telepovs.com`)'
      traefik.http.routers.telepovs.entrypoints: 'websecure'

networks:
  proxy:
    name: proxy
    external: true
