---
- name: Ensure required directories exist
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "u=rwx,g=rx,o=rx"
  loop:
    - "{{ couchdb_app_path }}/data"
    - "{{ couchdb_app_path }}/config"
    - "{{ couchdb_app_path }}/log"

- name: Render docker-compose file from template
  ansible.builtin.template:
    src: docker-compose.yml.j2
    dest: "{{ couchdb_app_path }}/docker-compose.yml"
    mode: "u=rw,g=r,o=r"

- name: Restart container
  community.docker.docker_compose_v2:
    project_src: "{{ couchdb_app_path }}"
    recreate: always
    remove_orphans: true

- name: Ensure CouchDB system DB exists
  ansible.builtin.uri:
    url: "https://couchdb.{{ shadow_domain }}/{{ tablename }}"
    method: PUT
    user: "{{ gh_secrets.COUCHDB_USER }}"
    password: "{{ gh_secrets.COUCHDB_PASSWORD }}"
    force_basic_auth: true
    status_code: [201, 412]
  register: couchdb_create_system_db
  failed_when: couchdb_create_system_db.status not in [201, 412]
  loop:
    - _users
    - _replicator
    - _global_changes
  loop_control:
    loop_var: tablename
