---
- name: Create app directory
  ansible.builtin.file:
    path: "{{ apps_path }}/telepovs"
    state: directory
    mode: "u=rwx,g=rx,o=rx"

- name: Put docker-compose.yml
  ansible.builtin.copy:
    src: "docker-compose.yml"
    dest: "{{ apps_path }}/telepovs/docker-compose.yml"
    mode: "u=rw,g=r,o=r"

- name: Login to GHCR
  community.docker.docker_login:
    registry_url: ghcr.io
    username: "{{ gh_username }}"
    password: "{{ gh_secrets.GHCR_TOKEN }}"

- name: Recreate the container
  community.docker.docker_compose_v2:
    project_src: "{{ apps_path }}/telepovs"
    remove_orphans: true
    recreate: always
    pull: always

- name: Clean up dangling images
  community.docker.docker_prune:
    images: true
