name: Deploy a single role

on:
  repository_dispatch:
    types: [Deploy an external app]

jobs:
  deploy:
    name: Deploy ${{ github.event.repository_dispatch.repository }} -> ${{ github.event.client_payload.host }}
    runs-on: ubuntu-latest
    environment: production
    env:
      DEPLOY_HOST: ${{ github.event.client_payload.host }}
      DEPLOY_ADDRESS: ${{ github.event.client_payload.address }}
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show envs
        run: |
          echo "DEPLOY_HOST=${{ env.DEPLOY_HOST }}"
          echo "DEPLOY_ADDRESS=${{ env.DEPLOY_ADDRESS }}"
