name: Deploy a single role

on:
  repository_dispatch:
    types: [Deploy a single role]
  workflow_dispatch:
    inputs:
      role:
        description: 'Ansible role to deploy'
        required: true
      update_cache:
        description: 'Update Ansible packages'
        type: boolean
        default: false

jobs:
  deploy:
    name: Deploy ${{ github.event.inputs.role || github.event.client_payload.role }}
    runs-on: ubuntu-latest
    environment: production
    env:
      ROLE: ${{ github.event.inputs.role || github.event.client_payload.role }}
      UPDATE_CACHE: ${{ github.event.inputs.update_cache || github.event.client_payload.update_cache }}
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH
        run: |
          echo "${{ secrets.ANSIBLE_SSH_PRIVATE_KEY }}" > private_key.pem
          chmod 600 private_key.pem

      - name: Set up python dependencies
        run: echo ansible > requirements.txt

      - name: Install python with pip dependencies
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          cache: 'pip'

      - name: Install Ansible
        if: env.UPDATE_CACHE == true
        run: |
          pip install -r requirements.txt
          ansible-galaxy collection install community.docker

      - name: Run Ansible Playbook
        env:
          ANSIBLE_USER: ansible
          ANSIBLE_HOST_KEY_CHECKING: False
        run: |
          ansible-playbook \
          -e "role_to_deploy=${{ env.ROLE }}" \
          -e "gh_username=${{ github.repository_owner }}" \
          -e "gh_secrets_json_base64='$( \
            cat << 'EOF' \
            | sed -E 's|([^\\][^r])\\n|\1\\n|g' \
            | sed 's|\\r\\n|\\n|g' \
            | base64 --wrap=0
          ${{ toJson(secrets) }}
          EOF
          )'" \
          -e "gh_vars_json_base64='$( \
            cat << 'EOF' \
            | sed -E 's|([^\\][^r])\\n|\1\\n|g' \
            | sed 's|\\r\\n|\\n|g' \
            | base64 --wrap=0
          ${{ toJson(vars) }}
          EOF
          )'" \
          --private-key private_key.pem \
          playbooks/deploy_role.yml
